name: Validate CloudFormation and Dockerfile

on:
  pull_request:
    branches:
      - main

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cfn-lint --version
          cd cloudformation
          cfn-lint -t ./template.yml

  docker-validate:
    name: Validate  Dockerfile
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Validate Dockerfile
      run: |
        docker run --rm -i hadolint/hadolint < Dockerfile