name: Validate CloudFormation and Dockerfile

on:
  pull_request:
    branches:
      - main

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Testing with CFN Lint Command
        uses: scottbrenner/cfn-lint-action@v2
        with:
          command: cfn-lint -t ./cloudformation/template.yaml

  docker-validate:
    name: Validate  Dockerfile
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Validate Dockerfile
      run: |
        docker run --rm -i hadolint/hadolint < Dockerfile